apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secrets-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    gcpsm:
      projectID: playground-s-11-7655b4b5
