{{- if .Values.postgres.enabled .Values.postgres.password }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  password: {{ .Values.postgres.password }}
{{- end }}
