apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gm-diploma-project-loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    chart: loki
    targetRevision: "6.24.0"
    helm:
      values: |
        deploymentMode: SingleBinary

        rbac:
          create: true

        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: 'filesystem'
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: index_
                  period: 24h
          podSecurityContext:
            fsGroup: 10001
            runAsGroup: 10001
            runAsUser: 10001

        alloy:
          enabled: true
          # Enable RBAC for the collector
          rbac:
            create: true
          controller:
            type: daemonset

          alloy:
            mounts:
              varlog: true
              dockercontainers: true
            
            config: |
              discovery.kubernetes "pods" {
                role = "pod"
              }

              discovery.relabel "pod_logs" {
                targets = discovery.kubernetes.pods.targets
                
                # 1. Construct the log path
                rule {
                  source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_name", "__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
                  separator     = ";"
                  regex         = "(.+);(.+);(.+);(.+)"
                  replacement   = "/var/log/pods/${1}_${2}_${3}/${4}/*.log"
                  target_label  = "__path__"
                }

                # 2. Promote labels for Grafana
                rule { source_labels = ["__meta_kubernetes_namespace"]; target_label = "namespace" }
                rule { source_labels = ["__meta_kubernetes_pod_name"]; target_label = "pod" }
                rule { source_labels = ["__meta_kubernetes_pod_label_app"]; target_label = "app" }
                rule { source_labels = ["__meta_kubernetes_pod_container_name"]; target_label = "container" }
              }

              # 3. Read the files
              local.file_match "pod_logs" {
                path_targets = discovery.relabel.pod_logs.output
              }

              loki.source.file "pod_logs" {
                targets    = local.file_match.pod_logs.targets
                forward_to = [loki.write.endpoint.receiver]
              }

              loki.write "endpoint" {
                endpoint {
                  url = "http://gm-diploma-project-loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push"
                }
              }

        gateway:
          enabled: true
        promtail:
          enabled: false

        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true