apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gm-diploma-project-alloy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    chart: alloy
    targetRevision: "0.11.0"
    helm:
      values: |
        rbac:
          create: true
        serviceAccount:
          create: true
        controller:
          type: daemonset

        alloy:
          extraVolumes:
            - name: varlog
              hostPath:
                path: /var/log
            - name: varlibdockercontainers
              hostPath:
                path: /var/lib/docker/containers
          
          extraVolumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true

          config: |
            discovery.kubernetes "all_pods" {
              role = "pod"
            }

            discovery.relabel "pod_logs" {
              targets = discovery.kubernetes.all_pods.targets
              
              rule {
                source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_name", "__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
                separator     = ";"
                regex         = "(.+);(.+);(.+);(.+)"
                replacement   = "/var/log/pods/${1}_${2}_${3}/${4}/*.log"
                target_label  = "__path__"
              }

              rule {
                source_labels = ["__meta_kubernetes_namespace"]
                target_label  = "namespace"
              }
              rule { source_labels = ["__meta_kubernetes_pod_name"]; target_label = "pod" }
              rule { source_labels = ["__meta_kubernetes_pod_label_app"]; target_label = "app" }
              rule { source_labels = ["__meta_kubernetes_pod_container_name"]; target_label = "container" }
            }

            loki.source.kubernetes "pods" {
              targets    = discovery.relabel.pod_logs.output
              forward_to = [loki.write.local.receiver]
            }

            loki.write "local" {
              endpoint {
                url = "http://gm-diploma-project-loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
              }
            }
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true