apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gm-diploma-project-alloy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    chart: alloy
    targetRevision: "0.11.0"
    helm:
      values: |
        alloy:
          config: |
            discovery.kubernetes "pods" {
              role = "pod"
            }

            discovery.relabel "pod_logs" {
              targets = discovery.kubernetes.pods.targets
              rule {
                source_labels = ["__meta_kubernetes_namespace"]
                target_label  = "namespace"
              }
              rule {
                source_labels = ["__meta_kubernetes_pod_name"]
                target_label  = "pod"
              }
              rule {
                source_labels = ["__meta_kubernetes_pod_container_name"]
                target_label  = "container"
              }
            }

            loki.source.kubernetes "all_pods" {
              targets    = discovery.relabel.pod_logs.output
              forward_to = [loki.write.local.receiver]
            }

            loki.write "local" {
              endpoint {
                url = "http://gm-diploma-project-loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
              }
            }
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true