apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gm-diploma-project-loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    chart: loki
    targetRevision: "6.24.0"
    helm:
      values: |
        deploymentMode: SingleBinary

        rbac:
          create: true
        serviceAccount:
          create: true

        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: 'filesystem'
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: index_
                  period: 24h
          podSecurityContext:
            fsGroup: 10001
            runAsGroup: 10001
            runAsUser: 10001

        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 10Gi
            storageClass: gp3

        gateway:
          enabled: true

        promtail:
          enabled: false
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
        resultsCache:
          enabled: false
        chunksCache:
          enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true