apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gm-diploma-project-karpenter
  namespace: argocd
  finalizers:                                      
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/MartinovG/DiplomaProject-ArgoCD.git
    targetRevision: main
    path: eu-central-1/karpenter
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true