apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: diploma-prod-db
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/GabrielMartinov/diplomaproject-argocd.git
    targetRevision: main
    path: eu-central-1/prod/databases 
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true