apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gm-diploma-project-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MartinovG/DiplomaProject-ArgoCD.git
    targetRevision: main
    path: eu-central-1/prod/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true