apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gm-diploma-prod-db-secret
  namespace: gm-diploma-project-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: gm-diploma-prod-db-secret
  data:
    - secretKey: password
      remoteRef:
        key: gm-diploma-project/prod-db
        property: password
