apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: grafana-admin-secret
  data:
    - secretKey: admin-user
      remoteRef:
        key: gm-diploma-project/grafana-admin
        property: username
    - secretKey: admin-password
      remoteRef:
        key: gm-diploma-project/grafana-admin
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-discord-webhook
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: alertmanager-discord-webhook
  data:
    - secretKey: webhook
      remoteRef:
        key: gm-diploma-project/alertmanager-config
        property: webhook-url
