apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/finalizer
spec:
  project: default
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    chart: kube-prometheus-stack
    targetRevision: "80.4.2"
    helm:
      values: |
        prometheusOperator:
          admissionWebhooks:
            enabled: false
          tls:
            enabled: false
        grafana:
          admin:
            existingSecret: grafana-admin-secret
            userKey: admin-user
            passwordKey: admin-password
          grafana.ini:
            dashboards:
              default_home_dashboard_path: /tmp/dashboards/app-overview.json
          additionalDataSources:
            - name: Loki
              type: loki
              uid: loki-ds-01
              url: http://gm-diploma-project-loki-gateway.monitoring.svc.cluster.local
              access: proxy
              isDefault: false
              jsonData:
                maxLines: 1000
                httpHeaderName1: "X-Scope-OrgID"
                derivedFields:
                  - datasourceUid: tempo-ds-01
                    matcherRegex: "traceID=(\\w+)"
                    name: TraceID
                    url: "$${__value.raw}"
              secureJsonData:
                httpHeaderValue1: "fake"
            - name: Tempo
              type: tempo
              uid: tempo-ds-01
              url: http://gm-diploma-project-tempo.monitoring.svc.cluster.local:3100
              access: proxy
              isDefault: false
              jsonData:
                tracesToLogsV2:
                  datasourceUid: loki-ds-01
                  filterByTraceID: true
                lokiSearch:
                  datasourceUid: loki-ds-01
          ingress:
            enabled: true
            ingressClassName: alb
            hosts: ["grafana-gmdiplomaproject.elsys.itgix.eu"]
            annotations:
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/target-type: ip
              alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
              alb.ingress.kubernetes.io/ssl-redirect: "443"
          persistence:
            enabled: true
            size: 10Gi

        prometheus:
          prometheusSpec:
            retention: 30d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 20Gi

        kubeControllerManager:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeProxy:
          enabled: false

        alertmanager:
          alertmanagerSpec:
            configSecret: alertmanager-discord-secret
      
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipSchemaValidation=true
    automated:
      prune: true
      selfHeal: true