apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    chart: kube-prometheus-stack
    targetRevision: "80.4.2"
    helm:
      values: |
        grafana:
          adminPassword: "pass1234"
          additionalDataSources:
            - name: Loki
              type: loki
              uid: loki-ds-01
              url: http://gm-diploma-project-loki-gateway.monitoring.svc.cluster.local
              access: proxy
              isDefault: false
              jsonData:
                maxLines: 1000
                derivedFields:
                  - datasourceUid: loki-ds-01
                    matcherRegex: "traceID=(\\w+)"
                    name: TraceID
                    url: "$${__value.raw}"
          ingress:
            enabled: true
            ingressClassName: alb
            hosts: ["grafana-gmdiplomaproject.elsys.itgix.eu"]
            annotations:
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/target-type: ip
              alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
              alb.ingress.kubernetes.io/ssl-redirect: "443"
          persistence:
            enabled: true
            size: 10Gi

        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 20Gi
        
        alertmanager:
          config:
            global:
              resolve_timeout: 5m
            route:
              group_by: ['alertname', 'job']
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 12h
              receiver: 'discord-notifications'
              routes:
                - match:
                    alertname: Watchdog
            receivers:
            - name: 'null'
            - name: 'discord-notifications'
              slack_configs:
              - api_url: 'https://discord.com/api/webhooks/1451569209124585634/Wjt2r2gmcXDRJKzbEllMa9SqHL1_uNmShXFId7zGvXEJxTGW1IG5PHAZjR5MOqdc3h8T/slack' 
                channel: '#alerts'
                send_resolved: true
                title: '{{ template "slack.default.title" . }}'
                text: '{{ template "slack.default.text" . }}'
                      
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipSchemaValidation=true
    automated:
      prune: true
      selfHeal: true