apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames: [monitoring]
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: NotIn
        values: [gateway]
      - key: service.kubernetes.io/headless
        operator: DoesNotExist
  endpoints:
    - port: http-metrics
      interval: 30s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki-canary
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames: [monitoring]
  selector:
    matchLabels:
      app.kubernetes.io/name: loki-canary
  endpoints:
    - port: http-metrics
      interval: 30s
      path: /metrics
