apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/finalizer
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "70.4.1"
    helm:
      releaseName: monitoring
      valuesObject:
        prometheus:
          prometheusSpec:
            retention: 6h
            replicas: 1
            resources:
              requests: { cpu: 200m, memory: 512Mi }
              limits: { cpu: "1", memory: 1Gi }
        grafana:
          adminPassword: sandbox-admin
          resources:
            requests: { cpu: 50m, memory: 128Mi }
            limits: { cpu: 200m, memory: 256Mi }
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: gce
            hosts: []
            path: /
            pathType: Prefix
        alertmanager:
          enabled: false
        additionalPrometheusRulesMap:
          gm-diploma-demo:
            groups:
              - name: gm-diploma-project
                rules:
                  - alert: PodCrashLooping
                    expr: rate(kube_pod_container_status_restarts_total[5m]) > 0
                    for: 5m
                    labels:
                      severity: warning
                    annotations:
                      summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} рестартира често"
                  - alert: PreviewNamespaceHighCPU
                    expr: sum(rate(container_cpu_usage_seconds_total{namespace=~"pr-.*"}[5m])) by (namespace) > 0.8
                    for: 10m
                    labels:
                      severity: info
                    annotations:
                      summary: "Preview {{ $labels.namespace }} гори CPU"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true